CREATE TABLE `SYS_ACCOUNT` (

`ID` varchar(32) NOT NULL COMMENT '主键ID',

/*`USER_NAME` varchar(300) NOT NULL COMMENT '用户名',*/

`LOGIN_NAME` varchar(300) NOT NULL COMMENT '登录名/账号',

`PASSWORD` varchar(32) NOT NULL COMMENT '密码',

`INS_DATE` date NULL COMMENT '插入时间',

`LAST_UPD_DATE` date NULL COMMENT '最后修改时间',

`DEL_FLAG` int(1) NULL COMMENT '删除区分',

`LAST_ACCOUNT_ID` varchar(32) NULL COMMENT '最后操作用户',

PRIMARY KEY (`ID`, `LOGIN_NAME`) 

) engine = Aria;


CREATE TABLE `SYS_ROLE` (

`ID` varchar(32) NOT NULL COMMENT '主键UUID',

`ROLE_NAME` varchar(300) NOT NULL COMMENT '角色名称',

`INS_DATE` date NULL COMMENT '插入时间',

`LAST_UPD_DATE` date NULL COMMENT '最后修改时间',

`DEL_FLAG` int(1) NULL COMMENT '删除区分',

`LAST_ACCOUNT_ID` varchar(32) NULL COMMENT '最后操作用户',

PRIMARY KEY (`ID`, `ROLE_NAME`) 

) engine = Aria;



CREATE TABLE `SYS_PERMISSION` (

`ID` varchar(32) NOT NULL COMMENT '主键UUID',

`PERMISSION_NAME` varchar(300) NULL COMMENT '权限名称',

`DESCRITPION` varchar(600) NULL COMMENT '权限描述',

`PERMISSION_URL` varchar(255) NOT NULL COMMENT '授权链接',

`PARENT_ID` varchar(32) NULL COMMENT '父权限UUID',

`INS_DATE` date NULL COMMENT '插入时间',

`LAST_UPD_DATE` date NULL COMMENT '最后修改时间',

`DEL_FLAG` int(1) NULL COMMENT '删除区分',

`LAST_ACCOUNT_ID` varchar(32) NULL COMMENT '最后操作用户',

PRIMARY KEY (`ID`, `PERMISSION_URL`) 

) engine = Aria;



CREATE TABLE `SYS_ACCOUNT_ROLE` (

`ID` varchar(32) NOT NULL COMMENT '主键UUID',

`ACCOUNT_ID` varchar(32) NOT NULL COMMENT '账号UUID',

`ROLE_ID` varchar(32) NOT NULL COMMENT '角色UUID',

`INS_DATE` date NULL COMMENT '插入时间',

`LAST_UPD_DATE` date NULL COMMENT '最后修改时间',

`DEL_FLAG` int(1) NULL COMMENT '删除区分',

`LAST_ACCOUNT_ID` varchar(32) NULL COMMENT '最后操作用户',

PRIMARY KEY (`ID`, `ACCOUNT_ID`, `ROLE_ID`) 

) engine = Aria;



CREATE TABLE `SYS_ROLE_PERMISSION` (

`ID` varchar(32) NOT NULL COMMENT '主键UUID',

`ROLE_ID` varchar(32) NOT NULL COMMENT '角色UUID',

`PERMISSION_ID` varchar(32) NOT NULL COMMENT '权限UUID',

`INS_DATE` date NULL COMMENT '插入时间',

`LAST_UPD_DATE` date NULL COMMENT '最后修改时间',

`DEL_FLAG` int(1) NULL COMMENT '删除区分',

`LAST_ACCOUNT_ID` varchar(32) NULL COMMENT '最后操作用户',

PRIMARY KEY (`ID`, `ROLE_ID`, `PERMISSION_ID`) 

) engine = Aria;



CREATE TABLE `SYS_ACCOUNT_DETAIL` (

`ID` varchar(32) NOT NULL COMMENT 'UUID',

`ACCOUNT_ID` varchar(32) NOT NULL COMMENT '账号UUID',

`USER_NAME` varchar(300) NULL COMMENT '用户名',

`USER_AGE` int(3) NULL COMMENT '用户年龄',

`TELE_PHONE` varchar(20) NULL COMMENT '座机',

`CELL_PHONE` varchar(11) NULL COMMENT '手机',

`EMAIL` varchar(300) NULL COMMENT '电子邮件',

`WECHART` varchar(300) NULL COMMENT '微信',

`SEX` int(1) NULL COMMENT '性别',

`INS_DATE` date NULL COMMENT '插入时间',

`LAST_UPD_DATE` date NULL COMMENT '最后修改时间',

`DEL_FLAG` int(1) NULL COMMENT '删除区分',

`LAST_ACCOUNT_ID` varchar(32) NULL COMMENT '最后操作用户',

PRIMARY KEY (`ID`, `ACCOUNT_ID`) 

) engine = Aria;





ALTER TABLE `SYS_ACCOUNT_ROLE` ADD CONSTRAINT `fk_SYS_ACCOUNT_ROLE_SYS_ACCOUNT` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `SYS_ACCOUNT` (`ID`);

ALTER TABLE `SYS_ACCOUNT_ROLE` ADD CONSTRAINT `fk_SYS_ROLE_SYS_ACCOUNT_ROLE` FOREIGN KEY (`ROLE_ID`) REFERENCES `SYS_ROLE` (`ID`);

ALTER TABLE `SYS_ACCOUNT_DETAIL` ADD CONSTRAINT `fk_SYS_ACCOUNT_DETAIL_SYS_ACCOUNT` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `SYS_ACCOUNT` (`ID`);

ALTER TABLE `SYS_ROLE_PERMISSION` ADD CONSTRAINT `fk_SYS_ROLE_SYS_ROLE_PERMISSION` FOREIGN KEY (`ROLE_ID`) REFERENCES `SYS_ROLE` (`ID`);

ALTER TABLE `SYS_ROLE_PERMISSION` ADD CONSTRAINT `fk_SYS_ROLE_PERMISSION_SYS_PERMISSION` FOREIGN KEY (`PERMISSION_ID`) REFERENCES `SYS_PERMISSION` (`ID`);



